version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - climbr_network

  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"
    env_file:
      - .env
    networks:
      - climbr_network
    depends_on:
      - rabbitmq

networks:
  climbr_network:
    driver: bridge
